// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD513GdIaECnt1fE4-mGHZibqKItcI5tLI',
    appId: '1:576430943460:web:f49f4c5a8eaa5a0752d0f1',
    messagingSenderId: '576430943460',
    projectId: 'borusan-db388',
    authDomain: 'borusan-db388.firebaseapp.com',
    databaseURL: 'https://borusan-db388-default-rtdb.firebaseio.com',
    storageBucket: 'borusan-db388.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOSzQs0cobaNnz00x7JJrq36yolCQPeE8',
    appId: '1:576430943460:android:bcb65a6c7b663b3b52d0f1',
    messagingSenderId: '576430943460',
    projectId: 'borusan-db388',
    databaseURL: 'https://borusan-db388-default-rtdb.firebaseio.com',
    storageBucket: 'borusan-db388.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsRacyWDEyChmriUgejXkFz3p9OcQnMPc',
    appId: '1:576430943460:ios:e7557439371b295252d0f1',
    messagingSenderId: '576430943460',
    projectId: 'borusan-db388',
    databaseURL: 'https://borusan-db388-default-rtdb.firebaseio.com',
    storageBucket: 'borusan-db388.appspot.com',
    iosClientId: '576430943460-958l2kgs6orjba0buudomkr5rdpegom9.apps.googleusercontent.com',
    iosBundleId: 'com.example.proje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsRacyWDEyChmriUgejXkFz3p9OcQnMPc',
    appId: '1:576430943460:ios:acc8cc22b437f67c52d0f1',
    messagingSenderId: '576430943460',
    projectId: 'borusan-db388',
    databaseURL: 'https://borusan-db388-default-rtdb.firebaseio.com',
    storageBucket: 'borusan-db388.appspot.com',
    iosClientId: '576430943460-d8fovd55abdbb65e8khv9ati9qsnn0ga.apps.googleusercontent.com',
    iosBundleId: 'com.example.proje.RunnerTests',
  );
}
